# Generated by Django 3.1.4 on 2021-01-01 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frus', '0003_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='issue',
            new_name='content',
        ),
    ]
